---
title: "R Notebook"
output: html_notebook
---

```{r message=FALSE}
library(knitr)
library(readtext)
library(corpora)
library(quanteda)
library(dplyr)
```


```{r}
#loading file 

BNC <- readtext("BNC/*.txt", docvarsfrom=c("filenames"), docvarnames = "id")

BNC_corpus <- corpus(BNC)

bnc_docvars <- data.frame(id = docvars(BNC_corpus)$id,stringsAsFactors = F)


# left join to find meta info from BNCmeta 
data(BNCmeta)
df_bnc_docvars <- data.frame(
  id = BNCmeta["id"],
  mode = BNCmeta["mode"],
  domain = BNCmeta["domain"],
  stringAsFactors = F) 

docvar_info <- left_join(bnc_docvars,df_bnc_docvars,by = c("id" = "id"))

# add docvars
docvars(BNC_corpus)$mode <- df_bnc_docvars$mode
docvars(BNC_corpus)$domain <- df_bnc_docvars$domain

#unique(df_bnc_docvars$domain)


BNC_sub_corpus <- corpus_subset(BNC_corpus,mode == "written")

BNC_select_domain <- c("social_science","world_affairs","arts","leisure","commerce_finance")

BNC_sub_corpus <- corpus_subset(BNC_sub_corpus,domain %in% BNC_select_domain)

BNC_dfm <- dfm(BNC_sub_corpus,stem = F,remove_punct = TRUE , tolower = T)

```


```{r}
OANC <- readtext("OANC/*.txt", docvarsfrom=c("filenames"))

OANC_corpus <- corpus(OANC)

OANC_dfm <- dfm(OANC_corpus,stem = F, remove_punct = TRUE , tolower = T)
```


```{r}
## 3. First Try: FRE (No Pre-process)


OANC_FRE <- textstat_readability(texts(OANC_corpus, groups = "docvar2"), "Flesch")

hist(OANC_FRE, breaks=1000, col="red",xlim = c(0,100))
print(length((OANC_FRE)))
print(mean(OANC_FRE))
print(var(OANC_FRE))
```

```{r}
BNC_FRE <- textstat_readability(texts(BNC_sub_corpus, groups = "id"), "Flesch")

hist(BNC_FRE, breaks=1000, col="red",xlim = c(0,100))
print(length((BNC_FRE)))
print(mean(BNC_FRE))
print(var(BNC_FRE))
```

```{r}
t.test(BNC_FRE,OANC_FRE)
```


```{r}

BNC_feature <- featnames(BNC_dfm)
OANC_feature <- featnames(OANC_dfm)
#words appear in both cropus 
joint_feature <- intersect(BNC_feature,OANC_feature)

#joint dfm 
BNC_joint_dfm <- dfm_select(BNC_dfm, features = joint_feature,remove_punct = TRUE)
OANC_joint_dfm <- dfm_select(OANC_dfm, features = joint_feature, remove_punct = TRUE)

# caluclate the % 
BNC_freq <- colSums(as.matrix(BNC_joint_dfm))
OANC_freq <- colSums(as.matrix(OANC_joint_dfm))

sum_BNC <- sum(BNC_freq)
sum_OANC <- sum(OANC_freq)

BNC_weight <- BNC_freq/sum_BNC
OANC_weight <- OANC_freq/sum_OANC
```
```{r}
a <- sort(BNC_freq,decreasing = TRUE)[101:200]
b <- sort(OANC_freq,decreasing = TRUE)[101:200]

```


```{r}
a <- sort(BNC_freq,decreasing = TRUE)[1:10000]
b <- sort(OANC_freq,decreasing = TRUE)[1:10000]

setdiff(names(sort(BNC_freq,decreasing = TRUE)[1:1000]),names(sort(OANC_freq,decreasing = TRUE)[1:1000]))



#newlist <- list(oldlist, list(someobj))

british_feature <- c()
american_feature <- c()
british_bucket <- c()
american_bucket <- c()
number_diff <- c()

for (i in 1:2) {
  british <-sort(BNC_freq,decreasing = TRUE)[1+((i-1)*100):100*i]
  american <- sort(OANC_freq,decreasing = TRUE)[1+((i-1)*100):100*i]
  
  british_feature <-c(british_feature,british) 
  american_feature <- c(american_feature,american)
  
}

length(setdiff(names(a),names(b))) == length(setdiff(names(b),names(a)))

sort(BNC_freq,decreasing = TRUE)[1+((i-1)*100):100*i]
```



